### PR TITLE
internal/wire: use set to determine which argument to use in zero-call injectors

### LINKED ISSUE #222: Missed return statement in generated code
### Bug description

Wire generates broken code. It generates function body without return statement.

### To Reproduce

Run `wire` with following file
```go
// +build wireinject

package storage

import "github.com/google/wire"

type MyInterface interface {
	Method()
}

type MyImplementation struct{}

func (MyImplementation) Method() {}

func XXX(MyImplementation) MyInterface {
	wire.Build(wire.Bind(new(MyInterface), new(MyImplementation)))
	return nil
}
```

It will generate following file
```go
// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package storage

// Injectors from missed_return.go:

func XXX(myImplementation MyImplementation) MyInterface {

}

// missed_return.go:

type MyInterface interface {
	Method()
}

type MyImplementation struct{}

func (MyImplementation) Method() {}
```

## Expected behavior

Wire should generate following file
```go
//+build !wireinject

package storage

// Injectors from missed_return.go:

func XXX(myImplementation MyImplementation) MyInterface {
	return myImplementation
}

// missed_return.go:

type MyInterface interface {
	Method()
}

type MyImplementation struct{}

func (MyImplementation) Method() {}
```

### Version

github.com/google/wire v0.3.0
go version go1.13 darwin/amd64

### PR DESCRIPTION
**Pull request by zombiezen**
Fixes #222

### CODE REVIEW

File: internal/wire/wire.go [hunk 1]
```diff
@@ -643,12 +643,7 @@ func injectPass(name string, sig *types.Signature, calls []call, ig *injectorGen
 		}
 	}
 	if len(calls) == 0 {
-		for i := 0; i < params.Len(); i++ {
-			if types.Identical(injectSig.out, params.At(i).Type()) {
-				ig.p("\treturn %s", ig.paramNames[i])
-				break
-			}
-		}
+		ig.p("\treturn %s", ig.paramNames[set.For(injectSig.out).Arg().Index])
```
Comment (shantuo) [inline internal/wire/wire.go]: Could `Arg` panic here due to some user error? If so, it might be worth to add a better error message.

Comment (zombiezen) [reply internal/wire/wire.go]: Any error here should be due to a bug: the only reason that the zero-call case should be able to occur is when the injector function result should be coming directly from an argument.
